## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##   https://flox.dev/docs/reference/command-reference/manifest.toml/
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
# Core networking and debugging tools (Linux-specific)
netcat.pkg-path = "netcat"
netcat.systems = ["x86_64-linux", "aarch64-linux"]
nmap.pkg-path = "nmap"
nmap.systems = ["x86_64-linux", "aarch64-linux"] 
tcpdump.pkg-path = "tcpdump"
tcpdump.systems = ["x86_64-linux", "aarch64-linux"]
strace.pkg-path = "strace"
strace.systems = ["x86_64-linux", "aarch64-linux"]
lsof.pkg-path = "lsof"
lsof.systems = ["x86_64-linux", "aarch64-linux"]
# Process and system monitoring (cross-platform)
htop.pkg-path = "htop"
# SSL/TLS tools (cross-platform)
openssl.pkg-path = "openssl"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = '''
  # Barrier project initialization
  echo "🚀 Activating Barrier environment..."
  
  # Ensure log directory exists
  mkdir -p "$FLOX_ENV_PROJECT/logs"
  
  # Set up proper DISPLAY if not set
  if [ -z "${DISPLAY:-}" ]; then
    export DISPLAY=":0"
    echo "📺 Set DISPLAY to :0"
  fi
  
  # Check if barrier is installed
  if ! command -v barrierc >/dev/null 2>&1; then
    echo "⚠️  Barrier not found. Run: ./scripts/install.sh"
  else
    echo "✅ Barrier client ready: $(barrierc --version 2>&1 | head -1)"
  fi
  
  echo "📁 Project directory: $FLOX_ENV_PROJECT"
  echo "🔧 Available scripts:"
  echo "   ./scripts/install.sh      - Install dependencies"
  echo "   ./scripts/setup-client.sh - Configure client"  
  echo "   ./scripts/start-client.sh - Start client"
  echo "   ./scripts/debug-barrier.sh - Debug issues"
'''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell-specific customizations such as setting aliases go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ---------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## ------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Include ----------------------------------------------------------
## ... environments to create a composed environment
## ------------------------------------------------------------------
[include]
# environments = [
#     { dir = "../common" }
# ]


## Build and publish your own packages ------------------------------
##  $ flox build
##  $ flox publish
## ------------------------------------------------------------------
[build]
# [build.myproject]
# description = "The coolest project ever"
# version = "0.0.1"
# command = """
#   mkdir -p $out/bin
#   cargo build --release
#   cp target/release/myproject $out/bin/myproject
# """


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
# systems = [
#   "aarch64-darwin",
#   "aarch64-linux",
#   "x86_64-darwin",
#   "x86_64-linux",
# ]
# Uncomment to disable CUDA detection.
# cuda-detection = false
